version: '3'
services:
  mongo:
    container_name: mongo
    image: 'mongo:latest'
    environment:
      - MONGODB_DATABASE=sparkpost
    ports:
      - '27017:27017'
  app:
    container_name: sparkpost
    links:
      - mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      - 'MONGO_URL=mongodb://mongo/sparkpost'
